server:
  addrs:
    - http: 0.0.0.0:40772
  workers: 3

channels:

- name: ＮＨＫ総合・東京
  type: GR
  channel: '14'
- name: ＮＨＫＥテレ東京
  type: GR
  channel: '13'
- name: ｔｖｋ
  type: GR
  channel: '5'
- name: 日本テレビ
  type: GR
  channel: '12'
- name: テレビ朝日
  type: GR
  channel: '11'
- name: ＴＢＳ
  type: GR
  channel: '9'
- name: テレビ東京
  type: GR
  channel: '10'
- name: フジテレビジョン
  type: GR
  channel: '8'
- name: ＴＯＫＹＯ　ＭＸ
  type: GR
  channel: '3'
- name: 放送大学
  type: GR
  channel: '15'

  - name: BS朝日
  type: BS
  channel: BS01_0
  services: [151]
- name: BS朝日 (sub)
  type: BS
  channel: BS01_0
  services: [152]
- name: BS-TBS
  type: BS
  channel: BS01_1
  services: [161]
- name: BSジャパン
  type: BS
  channel: BS01_2
  services: [171]
- name: WOWOWプライム
  type: BS
  channel: BS03_0
  services: [191]
- name: NHK BSプレミアム
  type: BS
  channel: BS03_1
  services: [103]
- name: ディズニー・チャンネル
  type: BS
  channel: BS03_2
  services: [256]
- name: WOWOWライブ
  type: BS
  channel: BS05_0
  services: [192]
- name: WOWOWシネマ
  type: BS
  channel: BS05_1
  services: [193]
- name: BS11
  type: BS
  channel: BS09_0
  services: [211]
- name: スター・チャンネル1
  type: BS
  channel: BS09_1
  services: [200]
- name: TwellV
  type: BS
  channel: BS09_2
  services: [222]
- name: FOXスポーツ＆エンターテイメント
  type: BS
  channel: BS11_0
  services: [238]
- name: BSスカパー!
  type: BS
  channel: BS11_1
  services: [241]
- name: 放送大学BS2
  type: BS
  channel: BS11_2
  services: [232]
- name: 放送大学BS1
  type: BS
  channel: BS11_2
  services: [231]
- name: BS日テレ (sub)
  type: BS
  channel: BS13_0
  services: [142]
- name: BS日テレ
  type: BS
  channel: BS13_0
  services: [141]
- name: BSフジ
  type: BS
  channel: BS13_1
  services: [181]
- name: BSアニマックス
  type: BS
  channel: BS13_2
  services: [236]
- name: NHK BS1
  type: BS
  channel: BS15_0
  services: [101]
- name: NHK BS1 (sub)
  type: BS
  channel: BS15_0
  services: [102]
- name: スター・チャンネル2
  type: BS
  channel: BS15_1
  services: [201]
- name: スター・チャンネル3
  type: BS
  channel: BS15_1
  services: [202]
- name: グリーンチャンネル
  type: BS
  channel: BS19_0
  services: [234]
- name: J SPORTS 1
  type: BS
  channel: BS19_1
  services: [242]
- name: J SPORTS 2
  type: BS
  channel: BS19_2
  services: [243]
- name: イマジカBS・映画
  type: BS
  channel: BS21_0
  services: [252]
- name: J SPORTS 3
  type: BS
  channel: BS21_1
  services: [244]
- name: J SPORTS 4
  type: BS
  channel: BS21_2
  services: [245]
- name: BS釣りビジョン
  type: BS
  channel: BS23_0
  services: [251]
- name: 日本映画専門チャンネル
  type: BS
  channel: BS23_1
  services: [255]
- name: D-Life
  type: BS
  channel: BS23_2
  services: [258]

- name: ショップチャンネル/東映チャンネル/Mnet/日テレNEWS24
  type: CS
  channel: CS8
- name: 衛星劇場/KBW WORLD/スポーツライブ+/スカチャン1
  type: CS
  channel: CS10
- name: 映画ch・NECO/日テレG+/MONDO TV/日テレプラス
  type: CS
  channel: CS24
- name: ザ・シネマ/ファミリー劇場/スーパー！ドラマTV/ヒストリーチャンネル
  type: CS
  channel: CS14
- name: ムービープラス/ゴルフネットワーク/チャンネル銀河/女性ch／LaLa
  type: CS
  channel: CS18
- name: スカイA/時代劇専門ch/エンタメ～テレ/MTV
  type: CS
  channel: CS4
- name: GAORA/エムオン！/キッズステーション/ナショナルジオグラフィック
  type: CS
  channel: CS12
- name: SKY STAGE/AXN海外ドラマ/AXNミステリー/スペシャプラス/AT-X/BBCワールドニュース
  type: CS
  channel: CS16
- name: ホームドラマch/ミュージック・エア/歌謡ポップスch/カートゥーン/ディスカバリーチャンネル/アニマルプラネット/CNNj/囲碁・将棋
チャンネル
  type: CS
  channel: CS6
- name: TBSチャンネル1/テレ朝チャンネル1/テレ朝チャンネル2/ディズニージュニア
  type: CS
  channel: CS2
- name: QVC/TBSチャンネル2/FOX/TBS NEWS
  type: CS
  channel: CS22
- name: フジテレビONE/フジテレビTWO/フジテレビNEXT/スペースシャワーTV
  type: CS
  channel: CS20

tuners:

  # PLEX PX-W3U4/PX-Q3U4 & nns779/px4_drv

  - name: PX4-S0
    types: [BS, CS]
    command: recpt1 --b25 --lnb 15 --device /dev/px4video0 {{channel}} {{duration}} -

  - name: PX4-S1
    types: [BS, CS]
    command: recpt1 --b25 --lnb 15 --device /dev/px4video1 {{channel}} {{duration}} -

  - name: PX4-T0
    types: [GR]
    command: recpt1 --b25 --device /dev/px4video2 {{channel}} {{duration}} -

  - name: PX4-T1
    types: [GR]
    command: recpt1 --b25 --device /dev/px4video3 {{channel}} {{duration}} -

filters:
  post-filter: >-
    socat - tcp-connect:remote:40774
  # arib-b25-stream-test
